= Внедрение системы грейдов разработчиков в IT-компании

== Origin
https://www.youtube.com/watch?v=inWOE2nbYsA[Алексей Флоринский (СимбирСофт), РИТ++ 2017, Whale Rider, 6 июня]

В докладе рассказывается реальный опыт внедрения системы оценки знаний и опыта разработчиков, начиная от разработки самой системы оценки и заканчивая проработкой методов оценки. Система оценки уровня специалистов содержит в себе не только технические пункты, но и, в большей степени, оценку опыта и soft skills, что позволяет по-новому развивать систему обучения специалистов и строить индивидуальный план развития.

== Проблемы
* чему учить ньюкамера: теория, один проект, как можно больше проектов?
* закостенелость коллектива разработчиков
* разработчик хочет знать свой уровень
* руководитель одинаково оценивает специалистов
* трансляция ценностей компании

== Общая структура
Что не работает::
  ХХ баллов из 100 (например, 77% отвеченного на 100 вопросов), т.к. не показывает уровень погружения в материал.
джун может разбираться глубоко в каком-то вопросе, но плавать в остальном - итог, оценка не оч.

Ввели блоки, по каждому из которых есть грейд: джун, миддл, синиор, лид.

== Эволюция грейдов
=== Вариант 1
* полный тех. опросник по языку/фреймворку
* размер - 20-30 вопросов
* возможные ответы: да/нет

*Недостаток*: часто непонятно, чо ставить - ноль или один? (ведь нельзя поставить 0.5)

=== Вариант 2
* увеличили кол-во вопросов до 200
* упростили вопросы
* теперь проще ставить да/нет

*Недостаток*: нереально оценить коллектив (200 вопросов, 300 разрабов - дофига времени надо)

=== Вариант 3
* 50 вопросов
* еще раз улучшили формулировки
* ответ измеряется по шкале 1-50

*Недостаток*: те разработчкики, которые получили по данной шкале высокую оценку, в реальной жизни имели низкую эффективность

=== Вариант 4
Технических навыков недостаточно, поэтому добавили софт скиллс:

* умение работать в команде
* тимлидерство
* знание процессов и методологий
* коммуникативные навыки
* лидерские навыки

Это стало соответствовать реальности, т.к. в итогах технические блоки - это всего 2 из 7, составляющих итоговый грейд
В примере как раз видно, что оценка на тимлида 27%, а на синиора - всего 18%


== Методика оценки
* индивидуально: ментор и разработчик
* последовательный проход по чеклисту
* подробное обсуждение каждого пункта

IMPORTANT: Cотрудник должен согласиться с оценкой

Просто спросить и молчать - работало неверно, т.к. интроверт мог отвечать слишком сухо или сжато. +
Нужно задавать наводящие вопросы, чтобы раскрыть полноту знаний по теме. +
И оценка выставляется, если сотрудник согласен, что вот он чот знает, чот не знает, поэтому 7. Если не согласен, то типа ну ладно, 8. +
Без согласия сотрудник просто забьет на результаты и будет думать: "тут не школа, как работал, так и продолжу работать"

== Проверка корректности
* случайная выборка сотрудников
* привлекаем других менторов
* сравниваем получаемые оценки*

== Оценка vs вклад в компанию
* сравнение спецов с одинаковым грейдом
* оцениваем вклад каждого в компанию
* если вклад разный - меняем грейд

Пример:

  Один хорошо закрывает таски, но малообщительный, а другой в крайне сложной ситуации на проекте, проект на грани срыва, его вводишь на этот проект и он делает так, что всё хорошо, то есть спасает проект на самой-самой последней его стадии.

== Варианты развития специалисты
* персональный ментор
* доп. цель на проекте
* тестовый/внутренний проект
* доклад по теме
* создание и проведение курса
* выражается в форме ИПР - индивидуальный план развития

== Преимущества внедрения
* разработчикам хорошо, когда есть система профессионального роста
* сотрудники знают своих экспертов
* рабочий способ выявления талантов
* более плотная работа руководителей с сотрудником
* появились ИПР, которые нужно исполнять
* HR получили новый канал информации как о сотруднике, так и о руководителей

== Наблюдаемые эффекты
* выгодно иметь общий низкий уровень по грейдам (должна быть сложная система грейдов, системы оценки знаний)
* молодые специалисты открывают для себя новое ("селективность индексов, покрывающие/непрокрывающие индексы")
* сложное внедрение - сопротивление - личный профит
* руководители резко научились выделять ключевых и делегировать, имея задачу оценить 30-50 специалистов
* несбалансированность по технологиям
* полное несочетание с уровнями других компаний
* ощутимое количество недовольных из-за низких оценок (но это наш "стандарт качества" разработчика)
* ключевые опытные специалисты - их не оценивать, а делать участниками системы (почему это важно - потому что эти люди имеют авторитет, неформальное лидерство)

== Затраты
* вся история с грейдами в нашей компании - около *одного года*
* создание опросника - примерно *неделя* на каждый вариант
* опрос всех разработчиков - *до месяца* на всю компанию
* анализ результатов и формирование ИПР - *месяц*
_(нет инфы о том, сколько сотрудников заняты фулл-тайм на каждом этапе)_

== Рецепт
* подумать *"Зачем это нужно?"*
* разработать опросники по формуле *"Soft Skills + Технологии"*
* четко *связать баллы и уровни* J, M, S(+вариации)
* внедрить в компании *"стандарт знаний разработчика"*
* хорошо подумать *"Стоит ли оценивать разработчиков?"*
* разработать *методику оценки + проверка знаний*
* регулярно проводить переоценки
* явно обозначить *бонусы*, если вырос уровень
* утвердить процесс оценки новичков

== Выводы
К зарплате вы это фактически не сможете привязать.

== Q&A
[qanda]
Достаточно ли теоретического опросника, чтобы оценить?::
Для того, чтобы оценить, эксперт должен быть на соточку везде.::

  В опросниках среди вопросов есть и касаемо практики, ссылки - какой проект, что конкретно и т.п.
Касаемо кто будет оценивать: оценивают руководители отдела - человек, который работает в компании 3-5 лет, который прошел массу проектов, но в целом я про них не могу сказать, что они все синиоры. Наверное, нет. Но они имеют вот этот самый управленческий опыт, предпринимательский подход. И он когда опрашивает человека, то он в большей степени ориентируется, мысленно, на результат: "А что если нам с тобой завтра в проект и надо будет делать кэширование?". И на уровне ощущений понимает: сделает человек это или нет?

СимбирСофт входит в РуСофт. Обращались ли вы в РуСофт за методологией (в ЭПАМ, Люксофт)? Готовы ли делиться своими опросниками?::

На самом деле в другие компании мы так явно не обращались, так вот чтоб поделились опытом, но вся эта история началась с того, что мы стали искать информацию и действительно первое с чем мы столкнулись - это был доклад человека, с которым мы связывались (это была девушка, которая рассказывала, как они внедряли систему грейдов в своей компании). И мы с ней связались, получили их образцы, она нам их действительно выслала, мы посмотрели как там у них устроено. Это дало нам хороший мысленный толчок "куда двигаться дальше?". +
То есть в итоге мы не взяли их систему, потому что она нам не понравилась (например пунктом, что синиор обязан иметь активный проект на гитхабе). Мы по-другому подходили, не требовали такого. +
Что касается поделиться своим: я когда составлял презентацию, то была мысль для каких-то софт скиллс показать наши опросники. Но в итоге я потом передумал. Почему? Потому что эти вопросы мы составляли в режиме мозгового штурма, собравшись втроем-впятером. В итоге это наша личная придумка, которая не факт, что с ней кто-то вообще может согласиться в других компаниях. +
Вот поэтому, скорее, поделиться - нет, рассказать - да.

Как у вас учитываются роли на проектах и различные скиллы, которые  напрямую не относятся к таким грейдам?::
И как у вас развивается эта система в сторону оценки менеджеров?::

Действительно, в коллективах бывают такие люди, которые, ну, душа компании. Пример: вот есть два верстальщика. С одним вообще никто не хочет работать, но он мега-профессионал. Другой - ну так, середнячок, но каждый ПМ хочет взять его к себе в команду, проектную группу. Потому что он вот так работает, что с ним так приятно работать, пусть у него меньше эффективность, но ничего страшного, я же ПМ, я выделю ему чуть больше времени, сдвину сроки, он всё равно сделает. Но зато вокруг него команда действительно сплоченная получается. Система грейдов это  никак не может учесть, действительно. Но что мы тут делаем, с тем же верстальщиком? Мы понимаем, что он вот такой особенный, но при этом знаем, что он вообще мечтает стать фронтэндером и мы для него разработали индивидуальный план развития. То есть система работает в плане обучения, но есть особенности, о которых мы знаем. +
Руководителей (руководителей отделов, топ-менеджмент) мы не оцениваем по этой системе. В нашей компании структура очень плоская. Вот есть отделы, их руководители, замы директора и директор. Всё, нет больше никаких уровней. Поэтому менеджерский состав очень маленьких, нет смысла его оценивать, это люди работающие с момента основания компании.+
А для менеджеров продуктов, проектов у нас есть KPI, разработанные, зафикированные - они работают. То есть эта система грейдов - только для разработчиков.

Заложен ли бюджет на extra mile активности, или же разработчики должны делать это в свое свободное время?::

Это оплачивается, если ты идешь на создание курса, по вечерам там сидишь, потом ведешь, преподаешь этот курс. То есть это всё человеку оплачивается по часам. Лимитов нет. Возможность полностью уйти в обучение есть, но у нас такого пока нет. Если у человека виден педагогический талант, то мы всяческими способами стараемся ему проектную активность снизить, а преподавательскую увеличить. Например, вот тебе 5 стажеров - такое кол-во никто не может вести, а ты можешь - давай, веди. То есть это пока полностью на усмотрение менеджеров.

Джуниор, миддл и синиор заполняют одну анкету?::

Да, проценты - это процент отвеченных вопросов по блокам джуниорских, мидловых и т.д. вопросов.
Единственное различие, что блок софт скиллов одинаков для всех разработчиков, меняются только технологические - .NET, PHP, Ruby и т.д.
И плюс мы отдельно сделали для QA.

У вас получается, что тим лид - это самый крутой?::

Нет, тим лид - это навык. То есть можно быть одновременно мидллом и тим лидом.

Каков разброc в компании по грейдам?::

Ну... это пирамида классическая: 30% джунов, 40% миддлов ну и оставшиеся там как-то так. То есть миддл - она самая жирная прослойка получается.


Вы упоминали про вклад каждого сотрудника в компанию, value. Это как-то денежно выражается?::

Отчасти, да. Плюс какой-то вклад, который можно увидеть явным образом. Вот спас проект. Вот как этот вклад оценить? Мы знаем, что человек может спасать проект. Для нас важна такая абилити, но оценить в цифрах её трудно.

Вы еще упоминали, что грейды открыты всем, но правильно я понимаю, что у вас система оплаты разработчиков - рейтовая. Как разработчики к этому отнеслись, что все теперь плюс-минус знают зарплаты друг друга?::

У нас грейды к зарплатам не привязаны.

Последний вопрос про объективность опросников. Эксперты - это люди, которые работают в компании или внешние?::

Нет, это люди из компании, про которых без всякой оценки известно, что это синиор разработчик. Вот мы их и привлекали, разделяя по технологиям и вместе создавали эти вопросы.
Именно поэтому этот эффект и был, я его обозначил, что странно, что вопросы создавались группами, а С++ оказался особенным (низкие, по сравнению с другими технологиями, грейды у сотрудников)

У нас есть схожие опросники, но к грейдам не привязано и цель другая - чтобы было 100%. То есть прошли опросники, получили срез знаний. А к вам вопрос такой: как вы делаете повторную оценку? Если вопросы те же самые, то человек, если он ответственный, то он на такие вопросы ответит.::
Вот есть блок вопросов по SQL и человек ответил 30%. Он их может запомнить и пойти что-то почитать, чтобы пойти на повторную оценку и получить 70%. Но мы-то понимаем, что это лайфхак, что он только почитал, но практически еще не умеет.
  Наше мнение: +
    1) если он даже и сделал так, то это всё равно хорошо, значит что-то в голове у него останется. +
    2) во время опроса не запрещается спросить: "а напиши-ка мне вот такой запрос прям щас на этом компьютере".

Есть ли у вас опыт составления опросников с вариантами ответов?::

Мы пробовали делать с вариантами ответов, но сразу же отказались. То есть у нас вопросы большей частью открытые, на рассуждение.

Подскажите, как вы оцениваете дизайнеров и тестировщиков?::

Дизайнеров мы не оцениваем, это направление у нас самое новое, всего 5 человек. Тестировщиков, как и говорил, точно так же, только состав технических в
